print("All About You Quiz")
name = input("Whats your name? ")
color = input("What is your favorite color? ")
eye_color = input("Whats your eye color?")
small_number = input("Pick a number from 1-10:").capitalize()
big_number = input("Pick a number from 100-1000:")
breakfast = input("What did you have for breakfast?").capitalize()
school = input("What school do you go to?")
year = input("What year is it?")
age = input("How old are you?")
subject = input("Whats your favorite subject in school?")
print("Hello", name, "! I also really like", color,". Its really cool that your eyes are", eye_color,"!" ,small_number, "and" ,big_number, "are very very specific numbers." ,breakfast, "sounds delicious!" )
print(school, "sounds like a pretty boring school. Is it really", year,"? Wow. your", age,". Your really old. I also really like" ,subject,"!"   )